version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bezary_db
    restart: always
    environment:
      POSTGRES_USER: bezary_user
      POSTGRES_PASSWORD: bezary_password
      POSTGRES_DB: bezary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: bezary_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
